from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg,
                                               NavigationToolbar2Tk)
from tkinter import *
def plotscatter():
    global r1
    panel = LabelFrame(r1, text="PLOT")
    panel.pack()
    x = list(map(int, e1.get().split(",")))
    y = list(map(int, e2.get().split(",")))
    fig = Figure(figsize=(12, 7), dpi=100)
    plot1 = fig.add_subplot(111)
    plot1.set_xlabel(e3.get())
    plot1.set_ylabel(e4.get())
    plot1.scatter(x, y)
    canvas = FigureCanvasTkAgg(fig, master=panel)
    canvas.draw()
    canvas.get_tk_widget().pack()
def plotline():
    global r1
    panel = LabelFrame(r1, text="PLOT")
    panel.pack()
    x = list(map(int, e1.get().split(",")))
    # y = list(map(int, e2.get().split(",")))
    fig = Figure(figsize=(12, 7), dpi=100)
    plot1 = fig.add_subplot(111)
    plot1.set_xlabel(e3.get())
    # plot1.set_ylabel(e4.get())
    plot1.plot(x)
    canvas = FigureCanvasTkAgg(fig, master=panel)
    canvas.draw()
    canvas.get_tk_widget().pack()
def plotbar():
    global r1
    panel = LabelFrame(r1, text="PLOT")
    panel.pack()
    x = list(map(int, e1.get().split(",")))
    y = list(map(int, e2.get().split(",")))
    fig = Figure(figsize=(12, 7), dpi=100)
    plot1 = fig.add_subplot(111)
    plot1.set_xlabel(e3.get())
    plot1.set_ylabel(e4.get())
    plot1.bar(x, y)
    canvas = FigureCanvasTkAgg(fig, master=panel)
    canvas.draw()
    canvas.get_tk_widget().pack()
def scatterplt():
    global root
    root.destroy()
    global r1
    r1 = Tk()
    r1.state("zoomed")
    # r1.geometry("1920x1080")
    frame = LabelFrame(r1)
    frame.place(width=1920, height=480)
    frame.pack()
    global e1, e2, e3, e4
    l1 = Label(frame, text="Enter X values", padx=20, font=("Consolas", 20))
    # l1.config(font=("Consolas", 20))
    l2 = Label(frame, text="Enter Y values", padx=20)
    l2.config(font=("Consolas", 20))
    e1 = Entry(frame, width=30, font=("Consolas", 28))
    e2 = Entry(frame, width=30, font=("Consolas", 28))
    v1 = Label(frame, text="Label =")
    v1.config(font=("Consolas", 20))
    v2 = Label(frame, text="Label =")
    v2.config(font=("Consolas", 20))
    e3 = Entry(frame, width=15, font=("Consolas", 20))
    e4 = Entry(frame, width=15, font=("Consolas", 20))
    submit = Button(frame, text="PLOT IT", bg="green", fg="white", width=20, height=3, command=plotscatter)
    l1.grid(row=0, column=0)
    e1.grid(row=0, column=1, padx=20, pady=10)
    v1.grid(row=0, column=2)
    e3.grid(row=0, column=3, padx=10)
    l2.grid(row=1, column=0)
    e2.grid(row=1, column=1, padx=20, pady=10)
    v2.grid(row=1, column=2)
    e4.grid(row=1, column=3, padx=10)
    submit.grid(row=2, column=1, pady=20)
    r1.mainloop()
def lineplt():
    global root
    root.destroy()
    global r1
    r1 = Tk()
    r1.state("zoomed")
    # r1.geometry("1920x1080")
    frame = LabelFrame(r1)
    frame.place(width=1920, height=480)
    frame.pack()
    global e1,  e3
    l1 = Label(frame, text="Enter X values", padx=20, font=("Consolas", 20))
    # l1.config(font=("Consolas", 20))
    #l2 = Label(frame, text="Enter Y values", padx=20)
    #l2.config(font=("Consolas", 20))
    e1 = Entry(frame, width=30, font=("Consolas", 28))
    #e2 = Entry(frame, width=30, font=("Consolas", 28))
    v1 = Label(frame, text="Label =")
    v1.config(font=("Consolas", 20))
    #v2 = Label(frame, text="Label =")
    #v2.config(font=("Consolas", 20))
    e3 = Entry(frame, width=15, font=("Consolas", 20))
    #e4 = Entry(frame, width=15, font=("Consolas", 20))
    submit = Button(frame, text="PLOT IT", bg="green", fg="white", width=20, height=3, command=plotline)
    l1.grid(row=0, column=0)
    e1.grid(row=0, column=1, padx=20, pady=10)
    v1.grid(row=0, column=2)
    e3.grid(row=0, column=3, padx=10)
    #l2.grid(row=1, column=0)
    #e2.grid(row=1, column=1, padx=20, pady=10)
    #v2.grid(row=1, column=2)
    #e4.grid(row=1, column=3, padx=10)
    submit.grid(row=2, column=1, pady=20)
    r1.mainloop()
def barplt():
    global root
    root.destroy()
    global r1
    r1 = Tk()
    r1.geometry("1920x1080")
    frame = LabelFrame(r1)
    frame.place(width=1920, height=480)
    frame.pack()
    global e1, e2, e3, e4
    l1 = Label(frame, text="Enter X values", padx=20)
    l1.config(font=("Consolas", 20))
    l2 = Label(frame, text="Enter Y values", padx=20)
    l2.config(font=("Consolas", 20))
    e1 = Entry(frame, width=30, font=("Consolas", 28))
    e2 = Entry(frame, width=30, font=("Consolas", 28))
    v1 = Label(frame, text="Label =")
    v1.config(font=("Consolas", 20))
    v2 = Label(frame, text="Label =")
    v2.config(font=("Consolas", 20))
    e3 = Entry(frame, width=15, font=("Consolas", 20))
    e4 = Entry(frame, width=15, font=("Consolas", 20))
    submit = Button(frame, text="PLOT IT", bg="green", fg="white", width=20, height=3, command=plotbar)
    l1.grid(row=0, column=0)
    e1.grid(row=0, column=1, padx=20, pady=10)
    v1.grid(row=0, column=2)
    e3.grid(row=0, column=3, padx=10)
    l2.grid(row=1, column=0)
    e2.grid(row=1, column=1, padx=20, pady=10)
    v2.grid(row=1, column=2)
    e4.grid(row=1, column=3, padx=10)
    submit.grid(row=2, column=1, pady=20)
    r1.mainloop()
root = Tk()
root.state("zoomed")
title = Label(root, text="Data Visualizer")
title.config(font=("Consolas", 44))
title.pack()
frame = LabelFrame(root, text="Plot Options", padx=100, pady=100)
frame.pack(padx=10, pady=10)
b1 = Button(frame, command=scatterplt)
b2 = Button(frame)
b3 = Button(frame)
b4 = Button(frame,command=lineplt)
b5 = Button(frame, command=barplt)
photo = PhotoImage(file="D:/chinnu/project photos/scatter plt.png")
photo2 = PhotoImage(file="D:/chinnu/project photos/hist.png")
photo3 = PhotoImage(file="D:/chinnu/project photos/pie.png")
photo4 = PhotoImage(file="D:/chinnu/project photos/lineplt.png")
photo5 = PhotoImage(file="D:/chinnu/project photos/bar.png")
b1.config(image=photo, width=255, height=180)
b2.config(image=photo2, width=250, height=180)
b3.config(image=photo3, width=250, height=180)
b4.config(image=photo4, width=250, height=180)
b5.config(image=photo5, width=250, height=180)
# myLabel.pack()
b1.grid(row=1, column=0)
# l1.grid(row=2, column=0)
b2.grid(row=1, column=2)
b3.grid(row=1, column=4)
b4.grid(row=2, column=1)
b5.grid(row=2, column=3)
root.mainloop()